@HostAddress = http://localhost:5082/api/courses
# @HostAddress = http://localhost:5082/api/coursemodules
# @HostAddress = http://localhost:5082/api/users
# @HostAddress = http://localhost:5082/api/enrollments
# @HostAddress = http://localhost:5082/api/activities
# @HostAddress = http://localhost:5082/api/documents
# @HostAddress = http://localhost:5082/api/teachers

GET {{HostAddress}}
Accept: application/json

###


GET {{HostAddress}}/0
Accept: application/json

###

DELETE {{HostAddress}}/1
Accept: application/json

###


PUT {{HostAddress}}/1
Accept: application/json

###


POST {{HostAddress}}
Accept: application/json

###
